language: java

dist: xenial

env:
  - TRAVIS_JDK=adopt@1.8.202-08
  - TRAVIS_JDK=adopt-openj9@1.8.212-03
  # IBM doesn't allow downloads, but openjdk-openj9 will also work.
  #- TRAVIS_JDK=ibm@1.8.0-5.35
  - TRAVIS_JDK=amazon-corretto@1.8.212-04.2
  # Java 11 JVMs
  - TRAVIS_JDK=adopt@1.11.28-0
  - TRAVIS_JDK=adopt-openj9@1.11.28-0
  # Oracle doesn't allow downloads, this will give "invalid header" error.
  #- TRAVIS_JDK=1.11.0-3
  - TRAVIS_JDK=openjdk@1.11.0-2
  - TRAVIS_JDK=amazon-corretto@1.11.0-3.7.1
  # Default JDK of xenial
  - TRAVIS_JDK=

before_install:
  - test -z "$TRAVIS_JDK" || curl -Ls https://git.io/jabba | bash
  - test -z "$TRAVIS_JDK" || . ~/.jabba/jabba.sh

install:
  # Only install and use JDK if it is set. If empty, use system JDK.
  - test -z "$TRAVIS_JDK" || jabba install "$TRAVIS_JDK";
  - test -z "$TRAVIS_JDK" || jabba use "$TRAVIS_JDK";
  # Print the JDK we are going to use.
  - java -Xmx32m -version
  # due to a bug, dependency resolve will try to resolve reactor projects from subfolders, although
  # excludeReactor=true is set.
  #  - ./mvnw dependency:resolve dependency:resolve-plugins
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

stages:
  - validations
  - test

jobs:
  include:
    - stage: validations
      name: "Code validations (checkstyle)"
      script: ./mvnw -V -B clean install -DskipTests=true -Pcheckstyle
      #    Disabled because checker constantly crashes.
      #    - stage: validations
      #      name: "Checker framework (Nullness checker)."
      #      script: ./mvnw -V -B clean install -DskipTests=true -Pchecker

    - stage: test
      name: "Test build with coverage report"
      script: ./mvnw -V -B clean install -Dmaven.javadoc.skip=true
      after_success: bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.jabba/jdk"

# Do not cache built artifacts.
before_cache:
  - rm -f "$HOME/.m2/repository/io/github/zchunk"
  # Legacy path
  - rm -f "$HOME/.m2/repository/de/bmarwell/zchunk"

