language: java

dist: xenial

env:
  - TRAVIS_JDK=adopt@1.8.202-08
  - TRAVIS_JDK=adopt-openj9@1.8.212-03
  - TRAVIS_JDK=ibm@1.8.0-5.35
  - TRAVIS_JDK=amazon-corretto@1.8.212-04.2
  # Java 11 JVMs
  - TRAVIS_JDK=adopt@1.11.28-0
  - TRAVIS_JDK=adopt-openj9@1.11.28-0
  - TRAVIS_JDK=1.11.0-3
  - TRAVIS_JDK=openjdk@1.11.0-2
  - TRAVIS_JDK=amazon-corretto@1.11.0-3.7.1

before_install: curl -Ls https://git.io/jabba | bash && . ~/.jabba/jabba.sh

install:
  - jabba install "$TRAVIS_JDK" && jabba use $_ && java -Xmx32m -version
  # due to a bug, dependency resolve will try to resolve reactor projects from subfolders, although
  # excludeReactor=true is set.
  #  - ./mvnw dependency:resolve dependency:resolve-plugins
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

stages:
  - validations
  - test
  - java11

jobs:
  include:
    - stage: validations
      name: "Code validations (checkstyle)"
      script: ./mvnw -B clean install -DskipTests=true -Pcheckstyle
    - stage: validations
      name: "Checker framework (Nullness checker)."
      script: ./mvnw -B clean install -DskipTests=true -Pchecker

cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.jabba/jdk"


